Added an endpoint to create a new user
lrparkinson/horoscopes-api pull request #3
Opened 2021-06-12 20:14 UTC by OmerElgoni

Made a start on the numerology stuff
I've left the password in for now since I'm not quite sure how we're dealing with that right now.

2021-06-14 15:11 UTC, thabovr requested changes

2021-06-14 15:11 UTC, thabovr commented on totally-legit-horoscopes-api/Controllers/UsersController.cs
> +            int year = dateOfBirth.Month;
Is this not supposed to be dateOfBirth.year

2021-06-14 15:11 UTC, thabovr commented on totally-legit-horoscopes-api/Controllers/UsersController.cs
> +            int day = dateOfBirth.Month;
Is this not supposed to be dateOfBirth.date

2021-06-14 15:11 UTC, thabovr commented on totally-legit-horoscopes-api/Controllers/UsersController.cs
> +            if (value == 11 || value == 22) //Master numbers
Rather make 11 and 22 as constants

2021-06-14 15:11 UTC, thabovr commented on totally-legit-horoscopes-api/DTOs/UserDTO.cs
> +        public DateTime Dob { get; set; }
dateOfBirth rather than dob

2021-06-14 15:11 UTC, thabovr commented on totally-legit-horoscopes-api/Models/User.cs
> +        public User(string Email,  string Password, DateTime Dob, int NthChild, Profession Profession, StarSign StarSign, Dinosaur FavoriteDinosaur, List<Hobby> Hobbies)
dateOfBirth rather than dob

2021-06-17 07:19 UTC, OmerElgoni commented on totally-legit-horoscopes-api/DTOs/UserDTO.cs
> +        public DateTime Dob { get; set; }
Changing this would require changing a lot of things in other places and I'm not certain that this won't break things elsewhere

2021-06-17 07:22 UTC, thabovr commented on totally-legit-horoscopes-api/DTOs/UserDTO.cs
> +        public DateTime Dob { get; set; }
I agree, let's rather leave it

2021-06-17 08:32 UTC, matthewpil approved these changes

2021-06-17 08:35 UTC, thabovr approved these changes

2021-06-17 08:36 UTC, merged